fragment SwapData on Swap {
  id
  timestamp
  pair {
    token0 {
      id
      symbol
    }
    token1 {
      id
      symbol
    }
  }
  from
  amount0In
  amount1In
  amount0Out
  amount1Out
  amountUSD
}
